# #####################################################################
# Automatically generated by qmake (2.01a) Mo. Aug 12 20:13:39 2013
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += debug

include(../shared/shared.pro)

# Input
SOURCES += main.cc \
    himage.cc
HEADERS += himage.h
